
##########服务端口配置##########
server:
  port: 8084
  tomcat:
    max-http-header-size: 20000
    max-connections: 30000
##########mybatis配置##########
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  config-location:  classpath:mybatis-config.xml
##########swaggerAPI配置##########
swagger:
  basePath: com.bit.soft.service.controller
##########分页插件配置##########
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql
##########debug日志配置##########
logging:
  level:
    com.bit.sc.module : debug
##########redis配置##########
redis:
#  hostName: 192.168.1.168
#  port: 9081
  hostName: 192.168.1.152
  port: 6379
  timeout: 300
  maxIdle : 300
  maxTotal: 1000
  maxWaitMillis: 3000
  minEvictableIdleTimeMillis : 300000
  numTestsPerEvictionRun : 1024
  timeBetweenEvictionRunsMillis : 30000
  testOnBorrow : true
  testWhileIdle : true
##########数据库配置##########
spring:
  #  profiles:
  #    active: test
  datasource:
    #name: test
    url: jdbc:mariadb://127.0.0.1:3306/chuckweb?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    #初始化大小,最小,最大
    initialSize: 10
    minIdle: 10
    maxActive: 200
    # 配置获取连接等待超时的时间(毫秒
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  aop:
    auto: true
##########上传文件配置 start##########
file.pic: jpg,png,bmp,gif,jpeg
file.file: doc,docx,xls,xlsx,pdf,ppt,pptx,txt,zip,rar,arj,z
file.zip: zip,rar,arj,z

##Windows
##升级文件上传路径（本地存储，访问地址）
file:
  localtion: D:/fileInfo/headinfo/
  headUrl: /headinfo/
##升级文件上传路径（本地存储，访问地址）
versionPath: D:/fileInfo/version/
versionName: update.tar.gz
versionUp: http://192.168.1.185:8084/versionUpload/
#默认头像名称
defaultHead: default.png
#文件大小
servlet:
  multipart:
    max-file-size: 1Mb
    max-request-size: 1Mb
  ##########json配置 start##########
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  maxOpenPreparedStatements: 20
#accesstoken过期时间
accessExpTime: 3600
##########数据中心接口##########
dataCenter:
  address: http://192.168.1.152
  port9080: :8081
  port50001: :8001
  QuerySession:
    Query: /QuerySession/Query
    GetPic: /QuerySession/GetPic
    GetStat: /QuerySession/GetStat
  DataCenter:
    insert: /DataCenter/insert
  DataNodeMgr:
    AddDataNode: /DataNodeMgr/AddDataNode1
    DelDataNode: /DataNodeMgr/DelDataNode1
    UpdateDataNode: /DataNodeMgr/UpdateDataNode1
    GetDataNodes: /DataNodeMgr/GetDataNodes
    AddPlace: /DataNodeMgr/AddPlace1
    GetPlace: /DataNodeMgr/GetPlace
    DelPlace: /DataNodeMgr/DelPlace1

#############websocket配置##############
netty-websocket:
  host: 0.0.0.0
  path: /
  port: 81
  boss-loop-group-threads: 0
  worker-loop-group-threads: 0
  .use-compression-handler: false
  option.connect-timeout-millis: 30000
  option.so-backlog: 128
  child-option.write-spin-count: 16
  child-option.write-buffer-high-water-mark: 65536
  child-option.write-buffer-low-water-mark: 32768
  child-option.so-rcvbuf: -1
  child-option.so-sndbuf: -1
  child-option.tcp-nodelay: true
  child-option.so-keepalive: false
  child-option.so-linger: -1
  child-option.allow-half-closure: false
  reader-idle-time-seconds: 0
  writer-idle-time-seconds: 0
  all-idle-time-seconds: 0
  max-frame-payload-length: 65536

##  WebSocketLog  0开启   1关闭
WebSocketLog: 0
#客户端断开连接时，是否开启清除频道逻辑开关
cleanUpChannelSessionSwitch: false
###########默认初始密码##############
initPassword: 111111
callc: 0 0/5 * * * ?